In [40]:
import pandas as pd

df = pd.read_csv("../data/medquad.csv")
df.head()

,question,answer,source,focus_area
0,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...,NIHSeniorHealth,Glaucoma
1,What causes Glaucoma ?,"Nearly 2.7 million people have glaucoma, a lea...",NIHSeniorHealth,Glaucoma
2,What are the symptoms of Glaucoma ?,Symptoms of Glaucoma Glaucoma can develop in ...,NIHSeniorHealth,Glaucoma
3,What are the treatments for Glaucoma ?,"Although open-angle glaucoma cannot be cured, ...",NIHSeniorHealth,Glaucoma
4,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...,NIHSeniorHealth,Glaucoma

In [41]:
df = df[['question', 'answer']].copy()
df = df.dropna()

In [42]:
df["input_text"] = "Answer medically: " + df["question"]
df["target_text"] = df["answer"]

In [43]:
print(df.columns)
print(df.head())

Index(['question', 'answer', 'input_text', 'target_text'], dtype='object')
                                 question  \
0                What is (are) Glaucoma ?
1                  What causes Glaucoma ?
2     What are the symptoms of Glaucoma ?
3  What are the treatments for Glaucoma ?
4                What is (are) Glaucoma ?

                                              answer  \
0  Glaucoma is a group of diseases that can damag...
1  Nearly 2.7 million people have glaucoma, a lea...
2  Symptoms of Glaucoma  Glaucoma can develop in ...
3  Although open-angle glaucoma cannot be cured, ...
4  Glaucoma is a group of diseases that can damag...

                                          input_text  \
0         Answer medically: What is (are) Glaucoma ?
1           Answer medically: What causes Glaucoma ?
2  Answer medically: What are the symptoms of Gla...
3  Answer medically: What are the treatments for ...
4         Answer medically: What is (are) Glaucoma ?

                                         target_text
0  Glaucoma is a group of diseases that can damag...
1  Nearly 2.7 million people have glaucoma, a lea...
2  Symptoms of Glaucoma  Glaucoma can develop in ...
3  Although open-angle glaucoma cannot be cured, ...
4  Glaucoma is a group of diseases that can damag...

In [44]:
def clean_answer(text):
    if isinstance(text, str):
        return ". ".join(text.split(".")[:3])
    return text 

df['answer'] = df['answer'].apply(clean_answer)

In [45]:
df["target_text"] = df["answer"]

In [46]:
df.head()

,question,answer,input_text,target_text
0,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...,Answer medically: What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...
1,What causes Glaucoma ?,"Nearly 2. 7 million people have glaucoma, a le...",Answer medically: What causes Glaucoma ?,"Nearly 2. 7 million people have glaucoma, a le..."
2,What are the symptoms of Glaucoma ?,Symptoms of Glaucoma Glaucoma can develop in ...,Answer medically: What are the symptoms of Gla...,Symptoms of Glaucoma Glaucoma can develop in ...
3,What are the treatments for Glaucoma ?,"Although open-angle glaucoma cannot be cured, ...",Answer medically: What are the treatments for ...,"Although open-angle glaucoma cannot be cured, ..."
4,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...,Answer medically: What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...

In [47]:
df.isnull().sum()

question       0
answer         0
input_text     0
target_text    0
dtype: int64

In [48]:
len(df)

16407

In [49]:
df.to_csv("../data/medquad_cleaned.csv", index=False)